# Generated by Django 3.1.13 on 2022-04-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('l', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=255)),
                ('tz', models.CharField(max_length=255)),
                ('request', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('bytes', models.CharField(max_length=255)),
                ('referer', models.CharField(max_length=255)),
                ('useragent', models.CharField(max_length=255)),
            ],
        ),
    ]
