# Generated by Django 4.0.3 on 2022-04-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apacheAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='l',
        ),
    ]
