# Generated by Django 4.0.3 on 2022-04-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apacheAPI', '0002_remove_log_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='tz',
        ),
    ]
